config/routes.rb
require 'sidekiq/web'
Rails.application.routes.draw do
  resources :book_issues, only:[:index]
  mount Sidekiq::Web => '/sidekiq'


   get '/edit', to: 'book_issues#edit'
  post '/book_issues/submit', to: 'book_issues#submit'



  resources :payments
  get 'wepay/index'
  get 'submit_book/index'
  get 'contact/index'
  mount LetterOpenerWeb::Engine, at: "/letter_opener" if Rails.env.development?
  get 'b_issued/index'
  root 'books#index'
  root 'books#edit'
  root 'books#form'
  root 'books#user_list'
  get "books/about_us"

  get 'book_issues/submit_book'
  get 'book_issues/perticular_user'
  root 'book_issues#perticular_user'
 # get "books/contact_us"
  get 'contact-us', to: "contact#contact_us", as:  :contact_us
  
  get '/search' => 'books#search', :as => 'search_page'
  devise_for :users,  controllers: { registrations: "registrations" }
  resources :books
  resources :book_issues
  resources :contacts, only: [:index, :new, :create]
  resources :submit_books
  resources :total_fines
  resources :registrations
  get '/payments/:action(/:payment_id)', :controller => 'payments'

  root :to => "wepay#index"
 
  #get "/paypal_url" => "books#paypal_url"
 # post 'welcome'
  #resources :welcome, only: [:index, :contact_us, :new, :create]

  get '/', :to => 'total_fines#index'
  post :create_total_fine, :to => 'total_fines#create_total_fine'
  post :capture_total_fine, :to => 'total_fines#capture_total_fine'
end

app/models/book.rb
class Book < ApplicationRecord
  #monetize :price
  has_one_attached :image
  belongs_to :user,  optional: true
  validates :name, presence: true
  validates :price, presence: true
  validates :author, presence: true
  validates :book_no, presence: true
  validates :image, presence: true 
  has_many :book_issues, dependent: :destroy
 # belongs_to :total_fine
  belongs_to :payment 
   



    def paypal_url(return_url)
      values = {
        :business => "sb-e3ua912102888@business.example.com",
        :cmd => '_book',
        :upload => 1,
        :return => return_url,
        :invoice => id
      }
      book_no.each_line do |b|
        values.merge!({
          #{}"amount_#{index=1}" => b.,
        "book_name" => b.name,
          "book_number" => b.id,
        })
      end
      # @books.each do |b|
      #    b.name
      #    b.price
      # end
  "https://www.sandbox.paypal.com/cgi-bin/webscr?" + values.to_query
end
end
     
     

app/controllers/books_controller.rb
class BooksController < ApplicationController
  before_action :set_book, only: [:show, :edit, :update, :destroy]

  def index
    @books = Book.paginate(:page => params[:page], :per_page => 12)
  end  

  def search
    if params[:search].blank?
      redirect_to(books_path, alert: "Empty field!") and return
    else
     keyword = params[:search]
     @books = Book.where("lower(name) LIKE ?", "%#{keyword}%")
   end
  end 

  def show
  #render js: "alert( #{params[:id]})"
  end

  def new
  @book = Book.new
 # @category = Book.map{|c| [c.name, c.id] }
  end

  def edit
  end

  def create
    @book = paypal_url(params)
    @book =Book.new(book_params)
    if @book.save
      #format.js
      redirect_to @book
    else
      render :new
    end
  end

  def paypal_url
   @book = paypal_url(return_url).book
  end

  def destroy
    #@book = Book.find(params[:id])
   @book.destroy
   
   respond_to do |format|
      format.html { redirect_to books_url }
      format.json { head :no_content }
      format.js   { render :layout => false }
   end
    # @book = Book.find(params[:id])
    #     @book.destroy!
    # redirect_to books_path
  end

  def book_total
    @book = Book.find(params[:id])
    @book.update(total_day-1)
  end 

  def update
    if @book.update_attributes(book_params)
      redirect_to @book
    else
      
      render 'edit'
    end
  end
  
  def issue
    @book_issue = BookIssue.find(params[:id])
  end  

  private

  def set_book
    @book = Book.find(params[:id])
  end

  def book_params
    params.require(:book).permit(:name, :price, :author, :book_no, :description, :image, :search, :Total, :bookcollection, :quantity)
  end
  end








































  # def index
  #     # @book_issues = BookIssue.all.where(user_id:current_user.id)
  #     #  @books.each do|book|
  #     #   @book_issue = BookIssue.find_by(book_id: book.id)
  #     #   #@users = @book_issue.users
  #     #  @user_id = @book_issue.user_id
  #     #   @user = User.find_by(@user_id)
  #     # end

  # end

app/helpers/book_helper.rb
module BookHelper
end

app/views/books/_form.html.erb
<div class="container">
  <%= bootstrap_form_with model: @book, local: true do |form| %>
 
    <% if @book.errors.any? %>
      <div id="error_explanation">
        <h2>
          <%= pluralize(@book.errors.count, "error") %> prohibited
          this book is already saved:
        </h2>
        <ul>
          <% @book.errors.full_messages.each do |msg| %>
            <li><%= msg %></li>
          <% end %>
        </ul>
      </div>
    <% end %>

    <p>
     <%= form.number_field :Total %>
    </p>

    <p>
      <%= form.text_field :name %>
    </p>
   
    <p>
      <%= form.text_area :price %>
    </p>

     <p>
      <%= form.text_area :author %>
    </p>
   
    <p>
      <%= form.text_area :book_no %>

    </p>

    <p>
      <%= form.text_area :description %>
    </p>

    <p>
      <%= form.file_field :image %>
    </p>

    <p>
      <%= form.submit %>
    </p>

  <% end %>
</div>

app/views/books/about_us.html.erb
<div class="container">
<div class="card-group">
  <div class="card">
   <div class="card bg-dark text-white">
    <div class="card-body">
<div align="center">About_us</div>
<h5 class="card-title">Book Infomation</h5>
 <p class="card-text">
	Library management system is best way to learn. its aim to be a part of online study material and book avaible to learn online and issue the book online. security provided in it for the users. if user want to login/logout so it do easily. and providing an count also how many books a user issued or not. that is trusted by its user for service excellence,

      library management systems to manage asset collections as well as relationships with their members. Library management systems help libraries keep track of the books and their checkouts, as well as users</p>
      <p class="card-text"><small class="text-muted">Update.time</small></p>
    </div>
  </div>
 </div> 
</div>
<div align="center">Our Team</div>

  <p class = "my-book-class">
     We provide Ruby on Rails development solutions to build custom web applications, web services, intranets, content management systems (CMS), single-page applications (SPA) and web portals using Ruby on Rails. We program applications, APIs, and other software to run on all operating systems using the Ruby programming language, Ruby on Rails framework, and RubyGems package manager. Our Ruby app development services lays out wire-frame designs, QA testing, debugging, and deployment.
  </p>
  

 <div class="card-group">
  <div class="card">
    <div class="card-body">
      <h5 class="card-title">Abhishek shere</h5>
      <p class="card-text"> Team Lead </p>
      <p class="card-text"><small class="text-muted"></small></p>
    </div>
  </div>

  <div class="card">
    <div class="card-body">
      <h5 class="card-title">Ajay jaitwal</h5>
      <p class="card-text">mentor</p>
      <p class="card-text"><small class="text-muted"></small></p>
    </div>
  </div>

  <div class="card">
    <div class="card-body">
      <h5 class="card-title">Poonam Ingle</h5>
      <p class="card-text">Admin</p>
      <p class="card-text"><small class="text-muted"></small></p>
    </div>
  </div>
</div>
</div>

app/views/books/destroy.js.erb
$('.delete_book').bind('ajax:success', function() {
   $(this).closest('tr').fadeOut();
});

app/views/books/edit.html.erb
<h1>Edit Book Information</h1>
 
<%= render 'form' %>
  
<%= button_to 'Back', books_path, class: "btn btn-primary" %>

app/views/books/index.html.erb
<div class="container">

  <h1>All Books</h1>
  <% if current_user.role == 'admin' %>
    <%= link_to 'New Book', new_book_path, class: "btn btn-outline-primary my-3" %>
  <% end %>
 
  <%= link_to 'Issued Books ', book_issues_path, class: 'btn btn-outline-primary'  %>

	<div class="row">
		<% @books.each do |book| %>
			<div class="col-md-3">
    		<div class="card" style="width: 18rem;">
	   			<%= image_tag book.image, height: 300, width: 285 if book.image.attached? %>
	        <div class="card-body">
						<h5 class="card-title">

							<%= link_to book.name, book_issues_path(book_id: book.id) %></h5>	  
	          <p class="card-text"><p><%= book.description.truncate(80) %></p>
	          <p><b><%= book.price %>$</b></p>
	          <p><%= link_to 'Issue Book', new_book_issue_path(book_id: book.id, user_id: current_user.id), class: "btn btn-outline-primary my-3" %></p>
						<p><%= link_to 'submit book',book_issues_submit_book_path(book_id: book.id), class: "btn btn-outline-primary my-3"%></p>  
	          <p class="card-text">Total book is: <%= book.Total %> 
	          	<% if @book_issues == @user %>
	          	  <% @book = book.Total-1 %>
	          	<%end%>  
	          </p>
	          <span><%= link_to 'Show', book_path(book), class: 'btn btn-outline-primary'  %></span> 
	          <% if current_user.role == 'admin' %>
	            <span><%= link_to 'Destroy', book_path(book),
	                      method: :delete,
	                      data: { confirm: 'Are you sure?' }, class: 'btn btn-outline-danger' %></span>
	            <span><%= link_to 'Edit', edit_book_path(book), class: 'btn btn-outline-warning'  %></span>

					    <div class="buy-now pv1 mt4 has-text-right">
					    	<script src="https://www.paypal.com/sdk/js?client-id=YOUR_CLIENT_ID&components=buttons,marks,messages="></script>

					       <%#= link_to image_tag("https://www.paypal.com/en_US/i/btn/btn_xpressCheckout.gif"), book.paypal_url(root_path)%>
					       <div id="paypal-button-container"></div>
					       <div class="buynow">
											      <paypal-button
											        refer="paypal-container-<%= book.id.to_s %>"
											      />
											    </div>
																      <%#= link_to 'checkout',  :class => 'btn btn-info btn-lg btn-block' %>
					    </div>
	          <% end %>

	        </div>
      	</div>
      </div>
		<% end %>
  </div>
  <div class="my-3">
		<%= will_paginate @books, renderer: WillPaginate::ActionView::BootstrapLinkRenderer %>
	</div> 
</div>

app/views/books/issue.html.erb
<div class="container">
  <h1>Issued Books</h1>
  <%= boatstrap_form_with model: @book_issue, local: true do |form| %>
    <p>
      <strong>User Id:</strong>
      <%= @book_issue.user_id %>
    </p>

    <p>
      <%= form.label :issue_date %><br>
      <%= form.date_field :issue_date %>
    </p>
   
    <p>
      <%= form.label :submit_date %><br>
      <%= form.date_field :submit_date %>
    </p>
    
  <% end %>
</div>

app/views/books/new.html.erb
<html>
<head>
  <h1>New book</h1>
</head>
<body>
<div class="container">

  <%= bootstrap_form_with scope: :books, url: books_path, local: true do |form| %>
 
    <p>
      <%#= select_tag(:book, options_for_select(@category), :prompt => "select add Category")%>
    </p>

    <p>
      <%= form.number_field :Total %>
    </p>
   
    <p>
      <%= form.text_field :name %>
    </p>
   
    <p>
      <%= form.text_area :price %>
    </p>

     <p>
      <%= form.text_area :author %>
    </p>

    <p>
      <%= form.text_area :book_no %>
    </p>

    <p>
      <%= form.text_area :description %>
    </p>

    <div>
    <p>
      <%= form.file_field :image %>
    </p>
    </div>
     
    <p>
      <%= form.submit %>
    </p>
  <% end %>
</div>
</body>
</html>

app/views/books/payment.html.erb
<div id="paypal-button"></div>
<script src="https://www.paypalobjects.com/api/checkout.js"></script>
<script>
  paypal.Button.render({
    // Configure environment
    env: 'sandbox',
    client: {
      sandbox: 'demo_sandbox_client_id',
      production: 'demo_production_client_id'
    },
    // Customize button (optional)
    locale: 'en_US',
    style: {
      size: 'small',
      color: 'gold',
      shape: 'pill',
    },

    // Enable Pay Now checkout flow (optional)
    commit: true,

    // Set up a payment
    payment: function(data, actions) {
      return actions.payment.create({
        transactions: [{
          amount: {
            total: '0.01',
            currency: 'USD'
          }
        }]
      });
    },
    // Execute the payment
    onAuthorize: function(data, actions) {
      return actions.payment.execute().then(function() {
        // Show a confirmation message to the buyer
        window.alert('Thank you for your purchase!');
      });
    }
  }, '#paypal-button');

</script>

app/views/books/search.html.erb
<body class="container" style="background: #f2f2f2"> 
  <h1 class="my-3" style="color: #6699ff;"><b>Searching result</b></h1>
  <div name="books">
   <div class="row">
    <% @books.each do |book| %>
    <div class="col-md-3">
     <div class="card" style="width: 18rem;">
       <%= image_tag book.image, height: 300, width: 285 if book.image.attached? %>
       <div class="card-body">
         <h5 class="card-title"><%= link_to book.name, @book_path %></h5>                     
         <p class="card-text"><p><%= book.description.truncate(80) %></p>
         <p><b><%= book.price %>$</b></p>
         <p><%= link_to 'Issue Book', new_book_issue_path(book_id: book.id, user_id: current_user.id), class: "btn btn-outline-primary my-3" %></p>
         <p class="card-text">Total book is: <%= book.Total %></p>
         <span><%= link_to 'Show', book_path(book), class: 'btn btn-outline-primary'  %></span>
         <% if current_user.role == 'admin' %>
         <span><%= link_to 'Destroy', book_path(book),
         method: :delete,
         data: { confirm: 'Are you sure?' }, class: 'btn btn-outline-danger' %></span>
         <span><%= link_to 'Edit', edit_book_path(book), class: 'btn btn-outline-warning'  %></span>
         <% end %>
       </div>
     </div>
   </div>
   <% end %>
 </div>
</body>

app/views/books/searchindex.erb
 <div class = "container">
	<div class="row">
		<% @books.each do |book| %>
		<div class="col-md-3">
			<div class="card" style="width: 18rem;">
				<%= image_tag book.image, height: 300, width: 285 if book.image.attached? %>
				<div class="card-body">
					<h5 class="card-title"><%= link_to book.name, @book_path %></h5>			            
					<p class="card-text"><p><%= book.description.truncate(80) %></p>
					<p><b><%= book.price %>$</b></p>
					<p><%= link_to 'Issue Book', new_book_issue_path(book_id: book.id, user_id: current_user.id), class: "btn btn-outline-primary my-3" %></p>
					<p class="card-text">Total book is: <%= book.Total %></p>
					<span><%= link_to 'Show', book_path(book), class: 'btn btn-outline-primary'  %></span>
					<% if current_user.role == 'admin' %>
					<span><%= link_to 'Destroy', book_path(book),
					method: :delete,
					data: { confirm: 'Are you sure?' }, class: 'btn btn-outline-danger' %></span>
					<span><%= link_to 'Edit', edit_book_path(book), class: 'btn btn-outline-warning'  %></span>
					<% end %>
				</div>
			</div>
		</div>
		<% end %>
	</div>
</div>  

app/views/books/show.html.erb
<div class="container my-3">
  <div>
    <% if @book.image.attached? %>
    <%= image_tag @book.image, height: 300, weight: 300 %>
    <% end %>
  </div>
<script>
    $(".container").click(function(){
       $("p").toggle();//{
      //   height: '150px',
      //   width: '150px'
      // });
    });
</script>
<style>
            button {
                background-color: cyan;
                height: 50px;
                width: 80px;
                padding: 20px;
            }

            button {border-radius: 12px;}
        </style>
<button id="toggle">Contant</button>

<!-- <button id="show">Show</button>     -->
   <%#= button_to 'contant show', class: 'btn btn-outline-primary'  %>
  <p>
    <strong>Name:</strong>
    <%= @book.name %>
  </p>
  
  <p>
    <strong>Price:</strong>
    <%= @book.price %>
  </p>

  <p>
    <strong>Author:</strong>
    <%= @book.author %>
  </p>

  <p>
    <strong>Book No:</strong>
    <%= @book.book_no %>
  </p>

  <p>
    <strong>Description:</strong>
    <%= @book.description %>
  </p>

  <p>
    <strong>Total:</strong>
    <%= @book.Total %>
  </p>
  
  <%= link_to 'back', books_path,  class: "btn btn-primary" %>

</div>

app/views/books/user_list.html.erb
<div class = "container">
	<%= @users.each do |user|%>
	<%= user.email %>
	<% end %>
	
	<%#= users.each do |user|%>
	<%#= user.id %>
	<%# end %>
</div>