config/routes.rb
require 'sidekiq/web'
Rails.application.routes.draw do
  resources :book_issues, only:[:index]
  mount Sidekiq::Web => '/sidekiq'


   get '/edit', to: 'book_issues#edit'
  post '/book_issues/submit', to: 'book_issues#submit'



  resources :payments
  get 'wepay/index'
  get 'submit_book/index'
  get 'contact/index'
  mount LetterOpenerWeb::Engine, at: "/letter_opener" if Rails.env.development?
  get 'b_issued/index'
  root 'books#index'
  root 'books#edit'
  root 'books#form'
  root 'books#user_list'
  get "books/about_us"

  get 'book_issues/submit_book'
  get 'book_issues/perticular_user'
  root 'book_issues#perticular_user'
 # get "books/contact_us"
  get 'contact-us', to: "contact#contact_us", as:  :contact_us
  
  get '/search' => 'books#search', :as => 'search_page'
  devise_for :users,  controllers: { registrations: "registrations" }
  resources :books
  resources :book_issues
  resources :contacts, only: [:index, :new, :create]
  resources :submit_books
  resources :total_fines
  resources :registrations
  get '/payments/:action(/:payment_id)', :controller => 'payments'

  root :to => "wepay#index"
 
  #get "/paypal_url" => "books#paypal_url"
 # post 'welcome'
  #resources :welcome, only: [:index, :contact_us, :new, :create]

  get '/', :to => 'total_fines#index'
  post :create_total_fine, :to => 'total_fines#create_total_fine'
  post :capture_total_fine, :to => 'total_fines#capture_total_fine'
end

app/models/payment.rb
class Payment < ApplicationRecord
	has_many :book_issues
	has_many :books
	#attr_accessible :email, :farm, :name, :produce, :produce_price, :wepay_access_token, :wepay_account_id, :password
	def wepay_authorization_url(redirect_uri)
  Wepay::Application::WEPAY.oauth2_authorize_url(redirect_uri, self.email, self.name)
end

# takes a code returned by wepay oauth2 authorization and makes an api call to generate oauth2 token for this farmer.
def request_wepay_access_token(code, redirect_uri)
  response = Wepay::Application::WEPAY.oauth2_token(code, redirect_uri)
  if response['error']
    raise "Error - "+ response['error_description']
  elsif !response['access_token']
    raise "Error requesting access from WePay"
  else
    self.wepay_access_token = response['access_token']
    self.save
  end
end

def has_wepay_access_token?
  !self.wepay_access_token.nil?
end

# makes an api call to WePay to check if current access token for farmer is still valid
def has_valid_wepay_access_token?
  if self.wepay_access_token.nil?
    return false
  end
  response = Wepay::Application::WEPAY.call("/user", self.wepay_access_token)
  response && response["user_id"] ? true : false
end

# creates a WePay account for this farmer with the farm's name
def create_wepay_account
  if self.has_wepay_access_token? && !self.has_wepay_account?
    params = { :name => self.farm, :description => "Farm selling " + self.produce }			
    response = Wefarm::Application::WEPAY.call("/account/create", self.wepay_access_token, params)

    if response["account_id"]
      self.wepay_account_id = response["account_id"]
      return self.save
    else
      raise "Error - " + response["error_description"]
    end

  end		
  raise "Error - cannot create WePay account"
end

end

app/controllers/payments_controller.rb
class PaymentsController < ApplicationController
  before_action :set_payment, only: %i[ show edit update destroy ]

  # GET /payments or /payments.json
  def index
    @payments = Payment.all
  end

  # GET /payments/1 or /payments/1.json
  def show
  end

  # GET /payments/new
  def new
    @payment = Payment.new
  end

  # GET /payments/1/edit
  def edit
  end

  # POST /payments or /payments.json
  def create
    @payment = Payment.new(payment_params)

    respond_to do |format|
      if @payment.save
        format.html { redirect_to payment_url(@payment), notice: "Payment was successfully created." }
        format.json { render :show, status: :created, location: @payment }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @payment.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /payments/1 or /payments/1.json
  def update
    respond_to do |format|
      if @payment.update(payment_params)
        format.html { redirect_to payment_url(@payment), notice: "Payment was successfully updated." }
        format.json { render :show, status: :ok, location: @payment }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @payment.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /payments/1 or /payments/1.json
  def destroy
    @payment.destroy

    respond_to do |format|
      format.html { redirect_to payments_url, notice: "Payment was successfully destroyed." }
      format.json { head :no_content }
    end
  end



  def oauth
  if !params[:code]
    return redirect_to('/')
  end

  redirect_uri = url_for(:controller => 'payments', :action => 'oauth', :payment_id => params[:payment_id], :host => request.host_with_port)
  @payment = Payment.find(params[:payment_id])
  begin
    @payment.request_wepay_access_token(params[:code], redirect_uri)
  rescue Exception => e
    error = e.message
  end

  if error
    redirect_to @payment, alert: error
  else
    redirect_to @payment, notice: 'We successfully connected you to WePay!'
  end
end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_payment
      @payment = Payment.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def payment_params
      params.require(:payment).permit(:password_hash, :pay)
    end
end

app/helpers/payments_helper.rb
module PaymentsHelper
end

app/views/payments/_form.html.erb
<%= simple_form_for(@payment) do |f| %>
  <%= f.error_notification %>
  <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>

  <div class="form-inputs">
    <%= f.input :password_hash %>
    <%= f.input :pay %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/payments/edit.html.erb
<h1>Editing Payment</h1>

<%= render 'form', payment: @payment %>

<%= link_to 'Show', @payment %> |
<%= link_to 'Back', payments_path %>

app/views/payments/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Payments</h1>

<table>
  <thead>
    <tr>
      <th>Password hash</th>
      <th>Pay</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @payments.each do |payment| %>
      <tr>
        <td><%= payment.password_hash %></td>
        <td><%= payment.pay %></td>
        <td><%= link_to 'Show', payment %></td>
        <td><%= link_to 'Edit', edit_payment_path(payment) %></td>
        <td><%= link_to 'Destroy', payment, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Payment', new_payment_path %>

app/views/payments/new.html.erb
<h1>New Payment</h1>

<%= render 'form', payment: @payment %>

<%= link_to 'Back', payments_path %>

app/views/payments/pay.html.erb
<h1>Buy <%= @farmer.produce %> from <%= @farmer.farm %> for <%= number_to_currency(@farmer.produce_price, :unit => "$") %></h1>
<p><%= link_to "← back to " + @farmer.name + "'s " + @farmer.farm, @farmer %></p>

<div id="wepay-iframe-div">
	<script type="text/javascript" src="https://www.wepay.com/js/iframe.wepay.js">
	</script>

	<script type="text/javascript">
		WePay.iframe_checkout("wepay-iframe-div", "<%= @checkout['checkout_uri'] %>");
	</script>
</div>

app/views/payments/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Password hash:</strong>
  <%= @payment.password_hash %>
</p>

<p>
  <strong>Pay:</strong>
  <%= @payment.pay %>
</p>

<% if (@is_admin && (!@payment.has_valid_wepay_access_token? || !@payment.has_wepay_account?)) %>
  <p>
    <b>Please create an account to manage your money: </b>
  <% redirect_uri = url_for(:controller => 'payments', :action => 'oauth', :payment_id => @payment.id, :host => request.host_with_port) %>
    <a class="btn btn-primary" href="<%= @payment.wepay_authorization_url(redirect_uri) %>">Click here to create your account</a>
  </p>
<% end %>


<h1><%= @payment.pay %></h1>


<%= link_to 'Edit', edit_payment_path(@payment) %> |
<%= link_to 'Back', payments_path %>