config/routes.rb
require 'sidekiq/web'
Rails.application.routes.draw do
  resources :book_issues, only:[:index]
  mount Sidekiq::Web => '/sidekiq'


   get '/edit', to: 'book_issues#edit'
  post '/book_issues/submit', to: 'book_issues#submit'



  resources :payments
  get 'wepay/index'
  get 'submit_book/index'
  get 'contact/index'
  mount LetterOpenerWeb::Engine, at: "/letter_opener" if Rails.env.development?
  get 'b_issued/index'
  root 'books#index'
  root 'books#edit'
  root 'books#form'
  root 'books#user_list'
  get "books/about_us"

  get 'book_issues/submit_book'
  get 'book_issues/perticular_user'
  root 'book_issues#perticular_user'
 # get "books/contact_us"
  get 'contact-us', to: "contact#contact_us", as:  :contact_us
  
  get '/search' => 'books#search', :as => 'search_page'
  devise_for :users,  controllers: { registrations: "registrations" }
  resources :books
  resources :book_issues
  resources :contacts, only: [:index, :new, :create]
  resources :submit_books
  resources :total_fines
  resources :registrations
  get '/payments/:action(/:payment_id)', :controller => 'payments'

  root :to => "wepay#index"
 
  #get "/paypal_url" => "books#paypal_url"
 # post 'welcome'
  #resources :welcome, only: [:index, :contact_us, :new, :create]

  get '/', :to => 'total_fines#index'
  post :create_total_fine, :to => 'total_fines#create_total_fine'
  post :capture_total_fine, :to => 'total_fines#capture_total_fine'
end

app/models/application_record.rb
require 'elasticsearch/model'

class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true

  include Elasticsearch::Model
  include Elasticsearch::Model::Callbacks

#   after_commit on: [:create] do
#   __elasticsearch__.create_index! force: true
# end

# after_commit on: [:update] do
#   __elasticsearch__.index_document
# end

# after_commit on: [:destroy] do
#   __elasticsearch__.delete_document
# end 
end

app/models/book.rb
class Book < ApplicationRecord
  #monetize :price
  has_one_attached :image
  belongs_to :user,  optional: true
  validates :name, presence: true
  validates :price, presence: true
  validates :author, presence: true
  validates :book_no, presence: true
  validates :image, presence: true 
  has_many :book_issues, dependent: :destroy
 # belongs_to :total_fine
  belongs_to :payment 
   



    def paypal_url(return_url)
      values = {
        :business => "sb-e3ua912102888@business.example.com",
        :cmd => '_book',
        :upload => 1,
        :return => return_url,
        :invoice => id
      }
      book_no.each_line do |b|
        values.merge!({
          #{}"amount_#{index=1}" => b.,
        "book_name" => b.name,
          "book_number" => b.id,
        })
      end
      # @books.each do |b|
      #    b.name
      #    b.price
      # end
  "https://www.sandbox.paypal.com/cgi-bin/webscr?" + values.to_query
end
end
     
     

app/models/book_issue.rb
class BookIssue < ApplicationRecord
 enum status: { pending: 0, failed: 1, paid: 2, paypal_executed: 3}
  enum payment_gateway: { stripe: 0, paypal: 1 }
  belongs_to :user
  belongs_to :book
 # before_save :set_total_fine
  #belongs_to :total_fine
  #belongs_to :submit_book
 # before_validation :set_total
# belongs_to :payment 


  scope :recently_created, ->  { where(created_at: 1.minutes.ago..DateTime.now) }

  def set_paid
    self.status = BookIssue.statuses[:paid]
  end
  def set_failed
    self.status = BookIssue.statuses[:failed]
  end
  def set_paypal_executed
    self.status = BookIssue.statuses[:paypal_executed]
  end




  
  # def total_fine
  #   if submit_date < total_day
  #      self.update(total_fine: 2*5)
  #   end   
  # end

  
    # private

    # def set_total_fine
    #   self[:total_fine] = total_fine
    # end  

     def paypal_url(return_url)
      values = {
        :business => 'sb-e3ua912102888@business.example.com',
        :cmd => 'book_issue',
        :upload => 1,
        :return => return_url,
      }
      
      "https://www.sandbox.paypal.com/in/signin" #+ values.to_query
    end



      #byebug

end
































# if submit_date
#   date find
#   time.now + 2
#   if submitted date is less and time .now is greater provide a maessage thankyou for submittion 
#   if submit_date is greater then total days than provide a fine message to pay expire 2*5 total fine 
#   issue book model. 
#Total_fine

app/models/contact.rb
class Contact < ApplicationRecord
	
end

app/models/payment.rb
class Payment < ApplicationRecord
	has_many :book_issues
	has_many :books
	#attr_accessible :email, :farm, :name, :produce, :produce_price, :wepay_access_token, :wepay_account_id, :password
	def wepay_authorization_url(redirect_uri)
  Wepay::Application::WEPAY.oauth2_authorize_url(redirect_uri, self.email, self.name)
end

# takes a code returned by wepay oauth2 authorization and makes an api call to generate oauth2 token for this farmer.
def request_wepay_access_token(code, redirect_uri)
  response = Wepay::Application::WEPAY.oauth2_token(code, redirect_uri)
  if response['error']
    raise "Error - "+ response['error_description']
  elsif !response['access_token']
    raise "Error requesting access from WePay"
  else
    self.wepay_access_token = response['access_token']
    self.save
  end
end

def has_wepay_access_token?
  !self.wepay_access_token.nil?
end

# makes an api call to WePay to check if current access token for farmer is still valid
def has_valid_wepay_access_token?
  if self.wepay_access_token.nil?
    return false
  end
  response = Wepay::Application::WEPAY.call("/user", self.wepay_access_token)
  response && response["user_id"] ? true : false
end

# creates a WePay account for this farmer with the farm's name
def create_wepay_account
  if self.has_wepay_access_token? && !self.has_wepay_account?
    params = { :name => self.farm, :description => "Farm selling " + self.produce }			
    response = Wefarm::Application::WEPAY.call("/account/create", self.wepay_access_token, params)

    if response["account_id"]
      self.wepay_account_id = response["account_id"]
      return self.save
    else
      raise "Error - " + response["error_description"]
    end

  end		
  raise "Error - cannot create WePay account"
end

end

app/models/submit_book.rb
class SubmitBook < ApplicationRecord
  # belongs_to :user
  # belongs_to :book
  # belongs_to :book_issue
end

app/models/total_book.rb
class TotalBook < ApplicationRecord
  belongs_to :book_issue
  belongs_to :book
 # belongs_to :submit_book
end

app/models/total_fine.rb
class TotalFine < ApplicationRecord
	has_many :books
	has_many :book_issues


	

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :books
  has_many :book_issues
  has_many :submit_books
  ##validates :book_issue
  enum role: [:user, :admin]

  after_initialize :set_default_role, :if => :new_record?

  def set_default_role
    self.role ||= :user
  end
end

app/models/welcome.rb
class Welcome < ApplicationRecord
	belongs_to :book
	belongs_to :book_issue
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/b_issued_helper.rb
module BIssuedHelper
end

app/helpers/book_helper.rb
module BookHelper
end

app/helpers/book_issue_helper.rb
module BookIssueHelper
end

app/helpers/contact_helper.rb
module ContactHelper
end

app/helpers/payments_helper.rb
module PaymentsHelper
end

app/helpers/submit_book_helper.rb
module SubmitBookHelper
end

app/helpers/total_fine_helper.rb
module TotalFineHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/helpers/wepay_helper.rb
module WepayHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>

<head>
  <title>LibraryManagement</title>
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>

  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
</head>

<body>
  <div class="book-index-grid pt4">
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
      <div class="container-fluid">
        <a class="navbar-brand" href="/books">Libarary</a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse margin-right" id="navbarSupportedContent">
          <ul class="navbar-nav me-auto mb-2 mb-lg-0">
            <li class="nav-item">
              <a class="nav-link active" aria-current="page" href="/books">Home</a>
            </li>
            <li class="nav-item">
              <a class="nav-link active" aria-current="page" href="/books/about_us">about us</a>
            </li>
            <li class="nav-item">
              <a class="nav-link active" aria-current="page" href="/contact-us">contact us</a>
            </li>
          </ul>
    <!-- <ul class= "navbar-form navbar-left">
     <li class = "dropdown">
     <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button"></a>
     </li>
   </ul>   -->
   <%= form_tag(search_page_path, :method => "get",   
   class: 'navbar-form navbar-left') do %>  
   <div class="input-group">  
    <%= search_field_tag :search, params[:search], placeholder: "Search", class: "form-control" %>  
    <div class="input-group-btn">  
      <%= button_tag "Search", :class => 'btn btn-primary glyphicon glyphicon-search',:name => nil%>  
    </div> 
  </div>  
  <% end %>
</div> 
</div>

<p class="navbar-text float-right">
  <% if user_signed_in? %>
  <!-- <p>you are a[<%#= current_user.role %>]</p> -->
  <strong><%= current_user.email %></strong>
  <%#= link_to book.name, users_path%>
  <%= link_to 'Edit profile', edit_user_registration_path, :class => 'btn btn-outline primary' %> |
  <%= button_to "Logout", destroy_user_session_path, method: :delete, :class => 'navbar-link'  %>
  <% else %>
  <%= link_to "Sign up", new_user_registration_path, :class => 'btn btn-outline primary'  %> |
  <%= button_to "Login", new_user_session_path, :class => 'navbar-link'  %>
  <% end %>
</p>
</div>


</nav>
<% if notice %>
<p class="alert alert-success"><%= notice %></p>
<% end %>
<% if alert %>
<p class="alert alert-danger"><%= alert %></p>
<% end %>

<%= yield %>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script>
</body>
</html>